- repo: https://github.com/mgedmin/pipreqs
  rev: v0.4.10
  hooks:
    - id: pipreqs
      name: Update requirements.txt
      language: python
      entry: pipreqs . --force
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.4
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [python, jupyter]
      args: ["--extend-select", "I", "--fix"]
    # Run the formatter.
    - id: ruff-format
      types_or: [python, jupyter]