import logging
import re
from importlib.resources import files

import pandas as pd

logger = logging.getLogger(__name__)

# Maps Grist/CSV "Type variabele" values to pandas dtype strings.
# This mapping belongs in code, not data — it's a fixed translation layer.
_DTYPE_MAP = {
    "number": "Float64",
    "date": "datetime64[ns]",
    "integer": "Int64",
    "string": "string",
    "boolean": "boolean",
}


def load_etdmodel() -> pd.DataFrame:
    """
    Load the ETD model definition from CSV.

    By default loads the bundled etdmap/data/etdmodel.csv. To use a custom
    model file, set etdmap.options.etdmodel_csv_path before importing this module:

        import etdmap
        etdmap.options.etdmodel_csv_path = "/path/to/my_model.csv"

    The CSV can be updated by any tooling that writes to that path — the
    derived structures (cumulative_columns, model_column_order, etc.) update
    automatically on next import.

    Returns
    -------
    pandas.DataFrame
        Full model DataFrame with all columns present in the CSV.
    """
    from etdmap import options

    if options.etdmodel_csv_path is not None:
        csv_path = options.etdmodel_csv_path
    else:
        csv_path = files("etdmap.data").joinpath("etdmodel.csv")

    return pd.read_csv(csv_path, dtype_backend="numpy_nullable")


def load_thresholds() -> pd.DataFrame:
    """
    Load thresholds from the bundled thresholds.csv.

    This file includes both primary-column thresholds and Diff-column thresholds
    (e.g. ElektriciteitNetgebruikHoogDiff) that are derived from cumulative columns
    and are not rows in etdmodel.csv. It can be regenerated from etdmodel.csv using
    the sync tooling in your workflow repository.

    Returns
    -------
    pandas.DataFrame
        Columns: Variabele, ThresholdType, Eenheid, Min, Max, ThresholdToelichting
    """
    thresholds_file = files("etdmap.data").joinpath("thresholds.csv")

    dtype_dict = {
        "Variabele": "string",
        "ThresholdType": "string",
        "Eenheid": "string",
        "Min": "Float64",
        "Max": "Float64",
        "ThresholdToelichting": "string",
    }

    return pd.read_csv(
        thresholds_file,
        dtype=dtype_dict,
        na_values=["n.a.", "NA", "N/A", ""],
        keep_default_na=True,
    )


def load_thresholds_as_dict() -> dict:
    """
    Load thresholds and return as {variable_name: {"Min": ..., "Max": ...}}.
    """
    thresholds_dict = {}
    for _, row in load_thresholds().iterrows():
        col = row["Variabele"]
        thresholds_dict[col] = {"Min": row["Min"], "Max": row["Max"]}
    return thresholds_dict


def load_unit_map() -> dict:
    """
    Return {Variabele: Eenheid} from the data model.

    Variables with NA Eenheid (e.g. metadata columns like ProjectIdBSV)
    are omitted so callers can use ``.get(col, "")`` semantics.

    Diff variants of Cumulatief == "ja" rows that are not themselves
    listed in the data model inherit the unit of their cumulative parent
    -- the model wins where it provides an explicit row.
    """
    df = load_etdmodel()
    unit_map: dict[str, str] = {}
    # Pass 1: trust the data model. Every Variabele with a non-NA
    # Eenheid populates the map directly.
    for variable, unit in zip(df["Variabele"], df["Eenheid"]):
        if pd.isna(variable) or pd.isna(unit):
            continue
        unit_map[str(variable)] = str(unit)
    # Pass 2: fill in Diff variants the data model doesn't list
    # explicitly by inheriting the cumulative parent's unit. Each
    # fallback emits a logging.warning so gaps in the data model
    # surface and can be closed by adding the missing row in Grist
    # (the source of truth -- the CSV is regenerated by sync). Existing
    # Diff rows from pass 1 are never touched.
    cum_mask = df["Cumulatief"].astype(str).str.strip().str.lower() == "ja"
    for variable, unit in zip(
        df.loc[cum_mask, "Variabele"], df.loc[cum_mask, "Eenheid"]
    ):
        if pd.isna(variable) or pd.isna(unit):
            continue
        diff_name = str(variable) + "Diff"
        if diff_name not in unit_map:
            logger.warning(
                "load_unit_map: %r is missing from the data model; "
                "inheriting unit %r from cumulative parent %r. Add an "
                "explicit row in Grist (source of truth) and re-sync to "
                "close this gap.",
                diff_name, str(unit), str(variable),
            )
            unit_map[diff_name] = str(unit)
    return unit_map


def get_aggregation_config() -> dict:
    """
    Return per-variable resampling and aggregation config from etdmodel.csv.

    Only includes variables where AggregatieMeenemen is True.

    Returns
    -------
    dict[str, dict[str, str]]
        Mapping of column name to::

            {
                "resample_method": str,   # ResamplingMethode: "sum", "avg", "max", ...
                "aggregate_method": str,  # AggregatieMethode: "avg", "sum", ...
            }

    Raises
    ------
    ValueError
        If any included variable is missing ResamplingMethode or AggregatieMethode
        in the model (model data incomplete -- fail hard per ADR-003).
    """
    df = load_etdmodel()
    included = df[df["AggregatieMeenemen"].fillna(False).astype(bool)]

    config = {}
    missing = []
    for _, row in included.iterrows():
        col = row["Variabele"]
        resample = row.get("ResamplingMethode", None)
        aggregate = row.get("AggregatieMethode", None)
        if pd.isna(resample) or resample == "":
            missing.append(f"{col}: ResamplingMethode")
        if pd.isna(aggregate) or aggregate == "":
            missing.append(f"{col}: AggregatieMethode")
        if missing:
            continue
        config[str(col)] = {
            "resample_method": str(resample),
            "aggregate_method": str(aggregate),
        }

    if missing:
        raise ValueError(
            f"etdmodel.csv is incomplete -- AggregatieMeenemen=True variables"
            f" missing required method columns: {missing}"
        )

    return config


# ---------------------------------------------------------------------------
# Derived structures — built once at import time from load_etdmodel().
# Change the CSV (or set etdmap.options.etdmodel_csv_path) to update these.
# ---------------------------------------------------------------------------

def _build_derived_structures():
    df = load_etdmodel()

    # Sort Prestatiedata rows by Volgorde when available, fall back to CSV row order.
    # Volgorde is an explicit integer sequence column that defines the canonical
    # ordering of performance variables. Maintain it in whatever tool manages
    # the CSV so ordering is intentional and stable, not an artifact of row insertion.
    perf = df[df["Entiteit"] == "Prestatiedata"].copy()
    if "Volgorde" in perf.columns and perf["Volgorde"].notna().any():
        perf = perf.sort_values("Volgorde", na_position="last")

    # Cumulative meter-reading columns.
    # Exclude date-type columns (ReadingDate may be flagged Cumulatief in some
    # CSV versions — filtering by type is more robust than filtering by name).
    # The order of this list does not affect correctness.
    cumulative = df[
        (df["Cumulatief"] == "ja") & (df["Type variabele"] != "date")
    ]["Variabele"].tolist()

    # Raw provider performance columns in Volgorde order — used to validate column
    # presence and to reorder output parquet files for INCOMING mapped data.
    # Scope: Entiteit == "Prestatiedata" ONLY.
    # Do NOT use this as the derivation target universe — use all_perf_cols below.
    # See etdmap/DECISIONS.md ADR-001 for the rationale.
    col_order = perf["Variabele"].tolist()

    # pandas dtype per performance column, derived from "Type variabele".
    col_types = {
        row["Variabele"]: _DTYPE_MAP.get(str(row["Type variabele"]), "Float64")
        for _, row in perf.iterrows()
        if pd.notna(row["Type variabele"])
    }

    # Columns suppliers are allowed to provide in their metadata files.
    supplier_meta = df[
        (df["Wie vult?"] == "Dataleverancier") & (df["Entiteit"] == "Metadata")
    ]["Variabele"].tolist()

    # All performance columns expected after the full pipeline has run:
    # both raw provider columns (Prestatiedata) and ETD-derived columns
    # (PrestatiedataBerekend). Used as the derivation target universe in
    # add_calculated_columns_adaptive(). See etdmap/DECISIONS.md ADR-001.
    perf_all = df[df["Entiteit"].str.startswith("Prestatiedata", na=False)].copy()
    all_perf_cols = perf_all["Variabele"].tolist()

    # Required subset: columns that must be present at end of pipeline.
    # Missing any of these after derivation is a data quality error (logging.error).
    required_perf_cols = perf_all[perf_all["Vereist"] == "ja"]["Variabele"].tolist()

    return cumulative, col_order, col_types, supplier_meta, all_perf_cols, required_perf_cols


(
    cumulative_columns,
    model_column_order,
    model_column_type,
    allowed_supplier_metadata_columns,
    all_performance_data_columns,
    required_performance_data_columns,
) = _build_derived_structures()

# data_analysis_columns: columns validated by dataset_validators.
# Currently an alias of model_column_order (all Prestatiedata rows).
# TODO: narrow to Vereist=="ja" once that column is fully populated in etdmodel.csv.
# A regression test in tests/test_data_model.py guards the current alias.
data_analysis_columns = model_column_order


# ---------------------------------------------------------------------------
# Tariff register pairs (Hoog/Laag) — derived from etdmodel.csv variable names.
# Hoog = peak tariff register, Laag = off-peak. Suppliers report either the
# combined root (single-tariff meter) or the split pair (multi-tariff meter).
# Consumers use these structures to reason about which side of a pair has data.
# In the future we expect to replace this with explicit metadata about pairs.
# ---------------------------------------------------------------------------

_TARIFF_RE = re.compile(r"^(?P<root>.+?)(?P<tariff>Hoog|Laag)(?P<suffix>Diff)?$")


def _build_tariff_register_pairs() -> tuple[dict[str, str], dict[str, tuple[str, str]]]:
    """
    Derive Hoog/Laag tariff register pair structures from etdmodel.csv.

    Returns
    -------
    (partners, root_to_splits)
        partners : dict[str, str]
            Symmetric flat partner map. Each Hoog or Laag variable name maps
            to its complementary partner (e.g. ElektriciteitNetgebruikHoog ->
            ElektriciteitNetgebruikLaag and vice versa). Includes Diff variants.
        root_to_splits : dict[str, tuple[str, str]]
            Maps the implied root variable name (Hoog/Laag suffix removed) to
            its (Hoog variant, Laag variant) tuple. The root is the conceptual
            combined-tariff column name; it may or may not exist as a separate
            variable in etdmodel.csv -- consumers typically check whether it
            appears in the data they are processing.
    """
    df = load_etdmodel()
    variables = set(df["Variabele"].dropna().astype(str))

    partners: dict[str, str] = {}
    root_to_splits: dict[str, tuple[str, str]] = {}

    for var in variables:
        m = _TARIFF_RE.match(var)
        if not m or m.group("tariff") != "Hoog":
            continue
        root = m.group("root")
        suffix = m.group("suffix") or ""
        laag_var = f"{root}Laag{suffix}"
        if laag_var not in variables:
            continue
        partners[var] = laag_var
        partners[laag_var] = var
        root_to_splits[root + suffix] = (var, laag_var)

    return partners, root_to_splits


tariff_partner_columns, tariff_root_to_splits = _build_tariff_register_pairs()

# TEST-ONLY: hand-curated subset of aggregation variables that test fixtures
# carry meaningful synthetic values for. Tests filter both the stored fixture
# and the freshly-generated pipeline output to this subset before comparing,
# so data-model expansion outside the subset does not break tests.
#
# Production code paths must NOT import this. Production aggregation pulls
# from get_aggregation_config() (sourced from etdmodel.csv via
# AggregatieMeenemen=True), and consumer entry points filter by what is
# actually present in the dataset via active_aggregation_variables(df) in
# etdtransform/aggregate.py. Using this list in production would lock the
# scope to whatever was last manually curated here, not what the data model
# currently says.
#
# Updating this list is a deliberate code change: extend it when you have
# added plausible synthetic ranges in the test fixture for the new variable
# and want the comparison surface to grow. The sync impact report in
# etdworkflow/sync_data_model.py highlights candidates from the data model
# that could be added here -- those candidates are informational only.
test_aggregation_columns: list[str] = [
    # Electricity grid exchange -- Diff variables (raw per-interval consumption)
    "ElektriciteitNetgebruikHoogDiff",
    "ElektriciteitNetgebruikLaagDiff",
    "ElektriciteitTerugleveringHoogDiff",
    "ElektriciteitTerugleveringLaagDiff",
    # Heat pump sub-system electricity -- Diff variables
    "ElektriciteitsgebruikWTWDiff",
    "ElektriciteitsgebruikWarmtepompDiff",
    "ElektriciteitsgebruikBoosterDiff",
    "ElektriciteitsgebruikBoilervatDiff",
    "ElektriciteitsgebruikRadiatorDiff",
    # Derived computed totals (produced by etdtransform, not present in raw parquet)
    "ZonopwekBruto",
    "TerugleveringTotaalNetto",
    "ElektriciteitsgebruikTotaalNetto",
    "Netuitwisseling",
    "ElektriciteitsgebruikTotaalWarmtepomp",
    "ElektriciteitsgebruikTotaalGebouwgebonden",
    "ElektriciteitsgebruikTotaalHuishoudelijk",
    "Zelfgebruik",
    "ElektriciteitsgebruikTotaalBruto",
]


# ---------------------------------------------------------------------------
# Indexed lookup dicts -- variables grouped by data-model column.
#
# Built once at import from etdmodel.csv. Use direct dict access at the call
# site; compose set operations there for combined filters rather than adding
# per-filter helpers here. Examples:
#
#     from etdmap.data_model import variables_by_categorie, variables_by_eenheid
#     temp_outdoor = sorted(
#         set(variables_by_eenheid.get("graden C", []))
#         & {v for v in variables_by_categorie.get("Temperatuur", []) if "Buiten" in v}
#     )
#     gj_heat = variables_by_eenheid.get("GJ", [])
#
# Values are sorted unique lists; keys are the raw Categorie / Eenheid
# strings as they appear in etdmodel.csv. Missing keys raise KeyError on
# bracket access -- use .get(key, []) for permissive callers.
# ---------------------------------------------------------------------------

def _build_indexed_lookups() -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    """
    Return ({Categorie: [Variabele,...]}, {Eenheid: [Variabele,...]}) from
    etdmodel.csv. Rows with NA in the index column are skipped.
    """
    df = load_etdmodel()
    by_cat: dict[str, set[str]] = {}
    by_unit: dict[str, set[str]] = {}
    for _, row in df.iterrows():
        var = row.get("Variabele")
        if pd.isna(var):
            continue
        var = str(var)
        cat = row.get("Categorie")
        if pd.notna(cat):
            by_cat.setdefault(str(cat), set()).add(var)
        unit = row.get("Eenheid")
        if pd.notna(unit):
            by_unit.setdefault(str(unit), set()).add(var)
    return (
        {k: sorted(v) for k, v in by_cat.items()},
        {k: sorted(v) for k, v in by_unit.items()},
    )


variables_by_categorie, variables_by_eenheid = _build_indexed_lookups()
